apiVersion: v1
kind: Namespace
metadata:
  name: lobo-entregas
---
apiVersion: v1
kind: Secret
metadata:
  name: lobo-secrets
  namespace: lobo-entregas
type: Opaque
stringData:
  JWT_SECRET: cambiar-en-produccion
